config/routes.rb
Rails.application.routes.draw do

  devise_for :users, :controllers => {
    :passwords => 'users/passwords'
  }

  devise_scope :user do
    get '/users/sign_out' => 'devise/sessions#destroy'
  end

  get "users/holiday" => "users#holiday"
  get "users/week_holiday_change" => "users#week_holiday_change"

  resources :users do
    resources :remaining_holiday, only:  [:new, :create, :edit, :update], shallow: true
    resources :notification, only:  [:create, :show, :destroy], shallow: true
  end
 
  root to: "holidays#index"

  resources :group do
    get 'change_holidays', to:'group#change_holidays'
    # resources :group_user, only:  [:show, :create, :destroy]

    get 'add_page' => 'group_user#show'
    post 'add_member' => 'group_user#create'
    # delete 'group_user/:id' => 'group_user#destroy'
  end

  # get "group/change_holidays_show" => "group#change_holidays_show"
  get "holidays/cancel_new" => "holidays#cancel_new"
  get "holidays/consecutive_holiday" => "holidays#consecutive_holiday"
  post "holidays/cancel_create" => "holidays#cancel_create"

  resources :holidays do
    resources :comments, only: [:create] 
    post 'agreement', to: 'request#agreement'
    post 'rejected', to: 'request#rejected'
  end
  

  resources :week_holiday_changes do
    post 'agreement', to: 'week_h_checks#agreement'
    post 'rejected', to: 'week_h_checks#rejected'
  end
end

app/models/holiday.rb
class Holiday < ApplicationRecord
     belongs_to :user
     has_many :requests, dependent: :destroy
     has_many :comments, dependent: :destroy
   

     with_options presence: true do
          validates :application_date 
          validates :acquisition_days 
          validates :reason        
     end

     def repuested_by?(user)
          requests.where(user_id: user.id).exists?
     end

     def yes_no?
          requests.where(yes_no: "no").exists?
     end
end

app/controllers/holidays_controller.rb
class HolidaysController < ApplicationController
     before_action :authenticate_user!
     before_action :set_current_user, only: [:index, :new, :edit, :show, :update, :consecutive_holiday]
     before_action :set_r_holiday, only: [:index, :new, :create, :edit, :show, :update, :cancel_new, :cancel_create, :consecutive_holiday]
     before_action :set_group, only: [:index, :new, :create]

     def index
          @holiday = current_user.holidays.all.order(updated_at: :desc).page(params[:page]).per(10)
          @week_holidays = current_user.WeekHolidayChanges.all.order(updated_at: :desc).page(params[:page]).per(10)
     end

     def new
          @holiday = Holiday.new
     end

     def create
          @holiday = Holiday.new(holiday_params)
          if @holiday.valid?
               holiday_calculation
               @holiday.save
               redirect_to root_path
          else
               render action: :new
          end
     end

     # 連休の申請をするためのページとそれを
     def consecutive_holiday
          @holiday = Holiday.new
     end

     def cancel_create
          @holiday = Holiday.new(holiday_params)
          if @holiday.valid?
               holiday_cancel_calculation
               @holiday.save
               redirect_to root_path
          else
               render action: :new
          end
     end

     def cancel_new
          @user = current_user
          @holiday = Holiday.new
     end

     def show
          @h = Holiday.find(params[:id])
          @request = Request.find_by(holiday_id: @h.id)
          @comment = Comment.new
          @comments = @h.comments
     end

     def edit
          @holiday = Holiday.find(params[:id])
     end
          
     def update
          @holiday = Holiday.find(params[:id])
          if @holiday.update(holiday_params)
               @holiday.requests.destroy_all
               holiday_calculation
               redirect_to holiday_path(@holiday.id)
          else
               render :new
          end
     end    

     def destroy
          @holiday = Holiday.find(params[:id])
          @holiday.destroy
          redirect_to root_path
     end

     

       

          
     private
     # ストロングパラメータ
     def holiday_params
          params.require(:holiday).permit(:application_date, :acquisition_days, :holiday_time_start, :holiday_time_end, :acquisition_time, :reason).merge(user_id: current_user.id)
     end 
 
     def set_current_user
          @user = current_user
     end

     def set_group
          @group = current_user.groups
     end


     def set_r_holiday
          @r = RemainingHoliday.find_by(user_id: current_user.id)
     end

     def find_group
          group_user = GroupUser.find_by(user_id: @h.user_id)
          group_id = group_user.group_id
          @group = Group.find_by(id: group_id)
     end

     def holiday_calculation
          if @holiday.acquisition_days == "時間休"
               if @r.changeable_time.to_i >= @holiday.acquisition_time.to_i
                    @r.changeable_time -= @holiday.acquisition_time.to_i
                    @r.time_limit -= @holiday.acquisition_time.to_i
               elsif @r.changeable_time.to_i < @holiday.acquisition_time.to_i && @r.working_hours == "7時間制"
                    @r.changeable_days -= 1
                    @r.changeable_time += (7 - @holiday.acquisition_time.to_i)
                    @r.time_limit -= @holiday.acquisition_time.to_i
               elsif @r.changeable_time.to_i < @holiday.acquisition_time.to_i && @r.working_hours == "8時間制"
                    @r.changeable_days -= 1
                    @r.changeable_time += (8 - @holiday.acquisition_time.to_i)
                    @r.time_limit -= @holiday.acquisition_time.to_i
               end
          elsif @holiday.acquisition_days.in?(["午前・半休", "午後・半休" ]) && @r.changeable_days >= 0.5
               @r.changeable_days -= 0.5
          elsif @holiday.acquisition_days == "1日" && @r.changeable_days >= 1
               @r.changeable_days -= 1
          end
          @holiday.time_record = @r.changeable_time
          @holiday.day_record = @r.changeable_days
          @r.save
     end

     def holiday_cancel_calculation
          if @holiday.acquisition_days == "時間休キャンセル"
               @r.changeable_time += @holiday.acquisition_time.to_i
               @r.time_limit += @holiday.acquisition_time.to_i
          elsif @holiday.acquisition_days == "半休キャンセル"
               @r.changeable_days += 0.5
          elsif @holiday.acquisition_days == "1日キャンセル" 
               @r.changeable_days += 1
          end
          @holiday.time_record = @r.changeable_time
          @holiday.day_record = @r.changeable_days
          @r.save
     end

     def reverse_calculation
          if @holiday.acquisition_days == "時間休"
               if @r.changeable_time.to_i >= @holiday.acquisition_time.to_i
                    @r.changeable_time += @holiday.acquisition_time.to_i
                    @r.time_limit += @holiday.acquisition_time.to_i
               elsif @r.changeable_time.to_i < @holiday.acquisition_time.to_i && @r.working_hours == "7時間制"
                    @r.changeable_days += 1
                    @r.changeable_time += (7 - @holiday.acquisition_time.to_i)
                    @r.time_limit += @holiday.acquisition_time.to_i
               elsif @r.changeable_time.to_i < @holiday.acquisition_time.to_i && @r.working_hours == "8時間制"
                    @r.changeable_days += 1
                    @r.changeable_time += (8 - @holiday.acquisition_time.to_i)
                    @r.time_limit += @holiday.acquisition_time.to_i
               end
          elsif @holiday.acquisition_days.in?(["午前・半休", "午後・半休" ]) && @r.changeable_days >= 0.5
               @r.changeable_days += 0.5
          elsif @holiday.acquisition_days == "1日" && @r.changeable_days >= 1
               @r.changeable_days += 1
          end
          @holiday.time_record = @r.changeable_time
          @holiday.day_record = @r.changeable_days
          @r.save
     end

end

app/helpers/holiday_helper.rb
module HolidayHelper
end

app/helpers/holidays_helper.rb
module HolidaysHelper
end

app/views/holidays/_header.html.erb
<div class="second-header">
  <div class="left-header">
    <div class="header-title">
      <% if current_page?(controller: 'holidays', action: 'index') %>
        <h2>マイページ（トップページ）</h2>
      <% elsif current_page?(controller: 'holidays', action: 'new') %>
        <h2>有給申請ページ</h2>
      <% elsif current_page?(controller: 'holidays', action: 'cancel_new') %>
        <h2>キャンセル申請ページ</h2>
      <% elsif current_page?(controller: 'holidays', action: 'consecutive_holiday') %>
        <h2>有給詳細ページ</h2>
      <% elsif current_page?(controller: 'holidays', action: 'edit') %>
        <h2>有給申請の編集ページ</h2>
      <% elsif current_page?(controller: 'holidays', action: 'show') %>
        <h2>有給詳細ページ</h2>
      <% end %>
    </div>
  </div>
  <div class="right-header">
    <div class="header-button">
      <% if current_user.position == "システム管理者"  %>
        <%= link_to "従業員一覧", users_path %>
      <% end %>
      <%= link_to "グループ一覧", group_index_path %>
      <%= link_to "有給申請一覧", users_holiday_path %>
      <%= link_to "週休変更一覧", week_holiday_changes_path %>
      <%= link_to "週休変更申請", new_week_holiday_change_path %>
      <%= link_to "有給の申請", new_holiday_path %>
      <%= link_to "有給の複数申請", holidays_consecutive_holiday_path %>
    </div>
  </div>
</div>

app/views/holidays/_holiday_form.html.erb
<%# <div class="holiday_form"> %>
  <%= form_with model: @holiday do |f| %>
    <% if RemainingHoliday.exists?(user_id: current_user.id) %>
      <h2 class="remaining_holiday">残り<%= @r.changeable_days  %>日<%= @r.changeable_time %>時間</h2>
        <table class="request-table">
          <tr>
            <th class="detail-item"><%= "申請日" %></th>
            <th class="detail-item"><%= "取得日(必須)" %></th>
            <th class="detail-item"><%= "有給のタイプ(必須)" %></th>
            <th class="detail-item"><%= "取得期間・時間" %></th>
            <th class="detail-item"><%= "取得時間(必須)" %></th>
            <th class="detail-item"><%= "事由(必須)" %></th>
          </tr>
          <tr>
            <td class="detail-value"><%= Date.today %></td>
            <td class="detail-value"><%= "" %><%= f.date_field :application_date %>
            <td class="detail-value"><%= f.select :acquisition_days,  ['時間休', '午前・半休', '午後・半休', '1日'],
            {include_blank: '---'} ,id:"holiday-acquisition-days"%></td>
            <td class="detail-value"><%= "start" %><%= f.time_field :holiday_time_start %>
                                    <%= "end" %><%= f.time_field :holiday_time_end %></td>
            <td class="detail-value"><%= f.number_field :acquisition_time %></td>
            <td class="detail-value"><%= f.text_area :reason %></td>
          </tr>
        </table>
    <%= f.submit "SEND" ,class:"send-btn"%>
    <% else %>
      <h3 class="remaining_holiday"><%= "まだ今年度の有給が記入されていません" %></h3>
    <% end %>
  <% end %>
<%# </div> %>

app/views/holidays/cancel_new.html.erb
<div class="container">
     <%= render partial: "header", locals: { user: @user } %>

     <%= form_with model: @holiday ,url:holidays_cancel_create_path do |f| %>
          <%= render 'shared/error_messages', model: f.object %> 
          <% if RemainingHoliday.exists?(user_id: current_user.id) %>
               <table class="request-table">
                    <tr>
                    <th class="detail-item"><%= "申請日" %></th>
                    <th class="detail-item"><%= "キャンセル日(必須)" %></th>
                    <th class="detail-item"><%= "有給のタイプ(必須)" %></th>
                    <th class="detail-item"><%= "キャンセル時間" %></th>
                    <th class="detail-item"><%= "事由(必須)" %></th>
                    </tr>
                    <tr>
                    <td class="detail-value"><%= Date.today %></td>
                    <td class="detail-value"><%= "" %><%= f.date_field :application_date %>
                    <td class="detail-value"><%= f.select :acquisition_days,  ['時間休キャンセル', '半休キャンセル', '1日キャンセル'],
                    {include_blank: '---'} ,id:"holiday-acquisition-days"%></td>
                    <td class="detail-value"><%= f.number_field :acquisition_time %></td>
                    <td class="detail-value"><%= f.text_area :reason, placeholder:"" %> </td>
                    </tr>
               </table>
               <%= f.submit "SEND" ,class:"send-btn"%>
          <% else %>
               <h3 class="remaining_holiday"><%= "まだ今年度の有給が記入されていません" %></h3>
          <% end %>
     <% end %>

</div>

app/views/holidays/consecutive_holiday.html.erb
<div class="container">
  <%= render partial: "header", locals: { user: @user } %>
  
  <%= form_with model: @holiday do |f| %>
    <% if RemainingHoliday.exists?(user_id: current_user.id) %>
      <h2 class="remaining_holiday">残り<%= @r.changeable_days  %>日<%= @r.changeable_time %>時間</h2>
        <table class="request-table">
          <tr>
            <th class="detail-item"><%= "申請日" %></th>
            <th class="detail-item"><%= "有休タイプ" %></th>
            <th class="detail-item"><%= "有休開始日(必須)" %></th>
            <th class="detail-item"><%= "有休最終日(必須)" %></th>
            <th class="detail-item"><%= "取得日数(必須)" %></th>
            <th class="detail-item"><%= "事由(必須)" %></th>
          </tr>
          <tr>
            <td class="detail-value"><%= Date.today %></td>
            <td class="detail-value"><%= f.select :acquisition_days,  ['複数日'],id:"holiday-acquisition-days"%></td>
            <td class="detail-value"><%= "" %><%= f.date_field :application_date %>
            <td class="detail-value"><%= "" %><%= f.date_field :application_date %>
            <td class="detail-value"><%= f.number_field :acquisition_time %></td>
            <td class="detail-value"><%= f.text_area :reason %></td>
            
          </tr>
        </table>
    <%= f.submit "SEND" ,class:"send-btn"%>
    <% else %>
      <h3 class="remaining_holiday"><%= "まだ今年度の有給が記入されていません" %></h3>
    <% end %>
  <% end %>
  
</div>

app/views/holidays/create.html.erb
<div class="contents row">
  <div class="success">
    <h3>有給休暇を申請しました。</h3>

    <%= link_to "トップページに", holidays_path %>
  </div>
</div>

app/views/holidays/edit.html.erb
<div class="container">
     <%= render partial: "header"%>
     <%= render partial: "holiday_form", local: true %>
     <%# <%= form_with model: @post, local: true do |f| %> 
          <%# <%= render :partial => 'holiday_form', :locals => {:f => f, :edit_flag => true} %>
     <%# <% end %> 

</div>

app/views/holidays/index.html.erb
<%= render partial: "header", locals: { user: @user } %>

<% if RemainingHoliday.exists?(user_id: current_user.id) %> 
     <div class="total_holiday">
          <div class="changeable-holiday">
               <h3>今年度付与分の有給休暇<%= @r.total_days %>日と<%= @r.total_time %>時間(申請分を差し引く前)</h3>
          </div>
          <div class="changeable-holiday">
               <% if RemainingHoliday.exists?(user_id: @user.id) %> 
                    <h3><%= @user.user_name %>さん  残り  <%= @r.changeable_days %>日と<%= @r.changeable_time %>時間  (申請分を差し引いた取得可能時間)</h3> 
               <% end %>
          </div>
     </div>
<% else %> 
     <div class="changeable-holiday">

          <h3>まだ今年度の有給が付与されていません。総務に連絡をください。</h3>
     </div>
<% end %>

     <div class="content-title">
               <h3>有給休暇の申請</h3> 
               <%= paginate @holiday %>
     </div>
     <div class="btn btn--orange">
               <%= link_to "キャンセル申請", holidays_cancel_new_path %>
     </div>

     <% if @holiday.exists? %> 
          <% @holiday.each do |f| %> 
               <%= link_to holiday_path(f.id), method: :get do %>
                    <table class="request-table">
                         <tr>
                              <th class="detail-item"><%= "申請日" %></th>
                              <th class="detail-item"><%= "取得日" %></th>
                              <th class="detail-item"><%= "有休タイプ" %></th>
                              <th class="detail-item"><%= "時〜時" %></th>
                              <th class="detail-item"><%= "取得時間" %></th>
                              <th class="detail-item"><%= "事由" %></th>
                              <th class="detail-item"><%= "残日数" %></th> 
                              <th class="detail-item"><%= "残時間" %></th> 
                         </tr>
                         <div class="formats">
                              <tr>
                                   <td class="detail-value"><%= f.updated_at.strftime('%Y/%m/%d') %></td>
                                   <td class="detail-value"><%= "" %><%= f.application_date.strftime('%Y/%m/%d') %>
                                   <td class="detail-value"><%= f.acquisition_days %></td>
                                   <% if f.holiday_time_start.nil? %> 
                                        <td class="detail-value"><span>ーー</span></td>
                                   <% else %>
                                        <td class="detail-value"><%= "start " %><%= f.holiday_time_start.strftime('%H') %>
                                                            <%= "〜end " %><%= f.holiday_time_end.strftime( "%H" ) %></td>
                                   <% end %> 
                                   <% if f.acquisition_time.nil? %> 
                                        <td class="detail-value"><span>ーー</span></td>
                                   <% else %>
                                        <td class="detail-value"><%= f.acquisition_time %>時間</td>
                                   <% end %>
                                   <td class="detail-value"><%= f.reason %></td>
                                   <td class="detail-value"><%= f.day_record  %>日</td>
                                   <td class="detail-value"><%= f.time_record %>時間</td>
                              </tr>
                         </div>
                    </table>   
               <% end %>
          <% end %>
               <div class="content-title">
               <%= paginate @holiday %>
               </div>
     <% else %>
          <div class='menber_name'>
               <h3>有休申請はまだありません</h3>
          </div>
     <% end %>  


     <div class="content-title">
               <h3>週休変更の申請</h3> 
     </div>


     <div class='item-info'>   
          <% if @week_holidays.exists? %> 
               <% @week_holidays.each do |f| %>
                    <% if WeekHolidayChange.where(id: f.id, user_id: @user.id).exists?%>
                         <%= link_to week_holiday_change_path(f.id), method: :get do %>
                              <table class="request-table">
                                   <tr>
                                        <th class="detail-item"><%= "名前" %></th>
                                        <th class="detail-item"><%= "申請日" %></th>
                                        <th class="detail-item"><%= "週休日" %></th>
                                        <th class="detail-item"><%= "変更日" %></th>
                                        <th class="detail-item"><%= "リーダー" %></th>
                                        <th class="detail-item"><%= "部長" %></th>
                                        <th class="detail-item"><%= "総務" %></th>
                                   </tr>
                                   <div class="formats">
                                        <tr>    
                                             <td class="detail-value"><%= f.user.user_name %></td>
                                             <td class="detail-value"><%= f.created_at.strftime('%Y/%m/%d') %></td>
                                             <td class="detail-value"><%= "" %><%= f.original_leave.strftime('%Y/%m/%d') %>
                                             <td class="detail-value"><%= f.changed_leave.strftime('%Y/%m/%d') %></td>
                                        

                                             <% if WeekHCheck.exists?(week_holiday_change_id: f.id) %>
                                                  <% if WeekHCheck.exists?(week_holiday_change_id: f.id, position: "リーダー") %>
                                                       <% check = WeekHCheck.find_by(week_holiday_change_id: f.id, position: "リーダー") %>
                                                       <% if check.yes_no == "yes" %>
                                                                 <td class="detail-value"><span>✅</span><%= check.user.user_name %></td>
                                                       <% elsif check.yes_no == "no" %>
                                                                 <td class="detail-value"><span>❌</span><%= check.user.user_name %></td>
                                                       <% end %>
                                                  <% else %>
                                                       <td class="detail-value"><span>--</span></td>
                                                  <% end %>

                                                  <% if WeekHCheck.exists?(week_holiday_change_id: f.id, position: "部長") %>
                                                       <% check = WeekHCheck.find_by(week_holiday_change_id: f.id, position: "部長") %>
                                                       <% if check.yes_no == "yes" %>
                                                       <td class="detail-value"><span>✅</span><%= check.user.user_name %></td>
                                                       <% elsif check.yes_no == "no" %>
                                                       <td class="detail-value"><span>❌</span><%= check.user.user_name %></td>
                                                       <% end %>
                                                  <% else %>
                                                       <td class="detail-value"><span>--</span></td>
                                                  <% end %>         

                                                  <% if WeekHCheck.exists?(week_holiday_change_id: f.id, position: "システム管理者") %>
                                                       <% check = WeekHCheck.find_by(week_holiday_change_id: f.id, position: "システム管理者") %>
                                                       <% if check.yes_no == "yes" %>
                                                       <td class="detail-value"><span>✅</span><%= check.user.user_name %></td>
                                                       <% elsif check.yes_no == "no" %>
                                                       <td class="detail-value"><span>❌</span><%= check.user.user_name %></td>
                                                       <% end %>
                                                  <% else %>
                                                       <td class="detail-value"><span>--</span></td>
                                                  <% end %> 
                                             <% else %>
                                                  <td class="detail-value"><span>--</span></td>
                                                  <td class="detail-value"><span>--</span></td>
                                                  <td class="detail-value"><span>--</span></td>
                                             <% end %>  
                                        </tr>
                                   </div>
                              </table>
                         <% end %>
                    <% end %>
               <% end %>
               <div class="content-title"><%= paginate @week_holidays %></div>
          <% else %>
               <div class='menber_name'>
                    <h3>週休の変更申請はまだありません</h3>
               </div>
          <% end %>     
     </div>

app/views/holidays/new.html.erb
<div class="container">
  <%= render partial: "header", locals: { user: @user } %>
  <%= render partial: "holiday_form", local: true %>
</div>

app/views/holidays/show.html.erb
<%= render partial: "header", locals: { user: @user } %>

<table class="request-table">
      <tr>
            <th class="detail-item"><%= "名前" %></th>
            <th class="detail-item"><%= "申請日" %></th>
            <th class="detail-item"><%= "取得日" %></th>
            <th class="detail-item"><%= "日/時" %></th>
            <th class="detail-item"><%= "時 〜 時" %></th>
            <th class="detail-item"><%= "時間" %></th>
            <th class="detail-item"><%= "事由" %></th>
            <th class="detail-item"><%= "リーダー" %></th>
            <th class="detail-item"><%= "部長" %></th>
            <th class="detail-item"><%= "総務" %></th>
      </tr>
      <div class="formats">
                  <tr>    
                        <td class="detail-value"><%= @h.user.user_name %></td>
                        <td class="detail-value"><%= @h.updated_at.strftime('%Y/%m/%d') %></td>
                        <td class="detail-value"><%= "" %><%= @h.application_date.strftime('%Y/%m/%d') %>
                        <td class="detail-value"><%= @h.acquisition_days %></td>
                        <% if @h.holiday_time_start.nil? %> 
                              <td class="detail-value"><span>--</span></td>
                        <% else %>
                              <td class="detail-value"><%= "" %><%= @h.holiday_time_start.strftime('%H:%M') %>
                                                <%= "〜 " %><%= @h.holiday_time_end.strftime( "%H:%M" ) %></td>
                        <% end %> 
                        <td class="detail-value"><%= @h.acquisition_time %>時間</td>
                        <td class="detail-value"><%= @h.reason %></td>

                        <% if Request.exists?(holiday_id: @h.id) %>
                              <% if Request.exists?(holiday_id: @h.id, position: "リーダー") %>
                                    <% request = Request.find_by(holiday_id: @h.id, position: "リーダー") %>
                                    <% if request.yes_no == "yes" %>
                                          <td class="detail-value"><span>✅</span><%= request.user.user_name %></td>
                                    <% elsif request.yes_no == "no" %>
                                          <td class="detail-value"><span>❌</span><%= request.user.user_name %></td>
                                    <% end %>
                              <% else %>
                                    <td class="detail-value"><span>--</span></td>
                              <% end %>

                              <% if Request.exists?(holiday_id: @h.id, position: "部長") %>
                                    <% request = Request.find_by(holiday_id: @h.id, position: "部長") %>
                              <% if request.yes_no == "yes" %>
                                    <td class="detail-value"><span>✅</span><%= request.user.user_name %></td>
                              <% elsif request.yes_no == "no" %>
                                    <td class="detail-value"><span>❌</span><%= request.user.user_name %></td>
                              <% end %>
                              <% else %>
                                    <td class="detail-value"><span>--</span></td>
                              <% end %>         

                              <% if Request.exists?(holiday_id: @h.id, position: "システム管理者") %>
                                    <% request = Request.find_by(holiday_id: @h.id, position: "システム管理者") %>
                              <% if request.yes_no == "yes" %>
                                    <td class="detail-value"><span>✅</span><%= request.user.user_name %></td>
                              <% elsif request.yes_no == "no" %>
                                    <td class="detail-value"><span>❌</span><%= request.user.user_name %></td>
                              <% end %>
                              <% else %>
                                    <td class="detail-value"><span>--</span></td>
                              <% end %> 
                        <% else %>
                              <td class="detail-value"><span>--</span></td>
                              <td class="detail-value"><span>--</span></td>
                              <td class="detail-value"><span>--</span></td>
                        <% end %>  
                  </tr>
      </div>
</table>

<div class="comment-area">
      <h2 class="content-title">コメント一覧</h2>
      <%# <br> %>
      <div class="comment-contest">
            <% unless @comments.blank? %>
                  <% @comments.each do |c| %>
                        <div  class="comment-contest">
                              <%= c.comment_content %>
                              ・
                              <%= c.user.user_name %>
                              ・
                              <%= c.created_at.strftime('%Y/%m/%d')  %>
                        </div>
                  <% end %>
            <% end %>
      </div>
      <%= form_for [@h, @comment] do |f| %>
            <%= f.text_field :comment_content %>
            <br>
            <br>
            <%= f.submit 'コメントする' %>
      <% end %>
</div>
      <div class="yes-no-btn">
            <% unless @h.repuested_by?(current_user) %>        <!-- ログインしているユーザーがリクエスト機能（承認・否認）を使ってなければOK -->  
                  <% if @h.yes_no? %>                          <!-- 自分はリクエスト機能を使っていないが、既に否認（NO）されている場合の処理 -->
                        <% if @h.user_id == current_user.id %> <!-- 投稿した本人なら、編集・削除できる。 -->
                              <%= "否認されているので、削除・編集する事ができます。"  %>
                                    <%= link_to "編集", edit_holiday_path(@h) %>
                                    ・
                                    <div class="btn btn--orange">
                                          <%= button_to "削除", holiday_path(@h), method: :delete %>
                                    </div>
                        <% end %>
                  <% else %>                    <!-- 自分はまだ承認していなくて、まだ否認もされていない場合。ログインユーザーのポジションが部長か総務のいずれか -->
                        <% unless @h.user_id == current_user.id %>
                              <% if current_user.position == "役員" || current_user.position == "システム管理者" %>
                                    <%# 部長と総務はグループに属していなくても承認できる。 %>
                                    <%=button_to "承認", holiday_agreement_path(@h.id), method: :post %>   
                                    <%=button_to "否認", holiday_rejected_path(@h.id), method: :post %>
                              <% elsif @user.position.in?(['リーダー', '主任', '部長']) || @h.user.groups.in?(current_user.groups) %>
                                          
                                    <% if (@h.user.groups.ids - current_user.groups.ids).size < @h.user.groups.ids.size %>
                                          <%# リーダーの所属しているグループidが、申請者のグループidを含んでいればOK %>
                                          <%=button_to "承認", holiday_agreement_path(@h.id), method: :post %>   
                                          <%=button_to "否認", holiday_rejected_path(@h.id), method: :post %>
                                    <% end %>
                              <% end %>
                        <% end %>
                  <% end %>
            <% end %>
      </div>