config/routes.rb
Rails.application.routes.draw do

  devise_for :users, :controllers => {
    :passwords => 'users/passwords'
  }

  devise_scope :user do
    get '/users/sign_out' => 'devise/sessions#destroy'
  end

  get "users/holiday" => "users#holiday"
  get "users/week_holiday_change" => "users#week_holiday_change"

  resources :users do
    resources :remaining_holiday, only:  [:new, :create, :edit, :update], shallow: true
    resources :notification, only:  [:create, :show, :destroy], shallow: true
  end
 
  root to: "holidays#index"

  resources :group do
    get 'change_holidays', to:'group#change_holidays'
    # resources :group_user, only:  [:show, :create, :destroy]

    get 'add_page' => 'group_user#show'
    post 'add_member' => 'group_user#create'
    # delete 'group_user/:id' => 'group_user#destroy'
  end

  # get "group/change_holidays_show" => "group#change_holidays_show"
  get "holidays/cancel_new" => "holidays#cancel_new"
  get "holidays/consecutive_holiday" => "holidays#consecutive_holiday"
  post "holidays/cancel_create" => "holidays#cancel_create"

  resources :holidays do
    resources :comments, only: [:create] 
    post 'agreement', to: 'request#agreement'
    post 'rejected', to: 'request#rejected'
  end
  

  resources :week_holiday_changes do
    post 'agreement', to: 'week_h_checks#agreement'
    post 'rejected', to: 'week_h_checks#rejected'
  end
end

app/models/week_holiday_change.rb
class WeekHolidayChange < ApplicationRecord
     belongs_to :user
     has_many :week_h_check, dependent: :destroy
end

app/controllers/week_holiday_changes_controller.rb
class WeekHolidayChangesController < ApplicationController
     before_action :authenticate_user!

     def index
          @week_holidays = WeekHolidayChange.all
     end

     def new
          @week_holiday = WeekHolidayChange.new
     end

     def create
          @week_holiday = WeekHolidayChange.new(week_holiday_params)
          if @week_holiday.valid?
               @week_holiday.save
               redirect_to week_holiday_changes_path
          else
               render action: :new
          end
     end

     def show
          @week_holiday = WeekHolidayChange.find(params[:id])
          @week_h_check = WeekHCheck.find_by(week_holiday_change_id: @week_holiday.id)
          # @comment = Comment.new
          # @comments = @h.comments
     end

     def edit
          @week_holiday = Holiday.find(params[:id])
     end
          
     def update
          @week_holiday = WeekHolidayChange.find(params[:id])
          if @week_holiday.update(week_holiday_params)
               @week_holiday.requests.destroy_all
               redirect_to week_holiday_change_path(@week_holiday.id)
          else
               render :new
          end
     end    

     def destroy
          @week_holiday = WeekHolidayChange.find(params[:id])
          @week_holiday.destroy
          redirect_to week_holiday_changes_path
     end


     private
     # ストロングパラメータ
     def week_holiday_params
          params.require(:week_holiday_change).permit(:original_leave, :changed_leave).merge(user_id: current_user.id)
     end 
end

app/helpers/week_holiday_changes_helper.rb
module WeekHolidayChangesHelper
end

app/views/week_holiday_changes/_form.html.erb
<%= form_with model: @week_holiday do |f| %>

     <table class="request-table">
          <tr>
               <th class="detail-item"><%= "申請日" %></th>
               <th class="detail-item"><%= "週休日" %></th>
               <th class="detail-item"><%= "変更日" %></th>
          </tr>
          <tr>
               <td class="detail-value"><%= Date.today %></td>
               <td class="detail-value"><%= "" %><%= f.date_field :original_leave %>
               <td class="detail-value"><%= "" %><%= f.date_field :changed_leave %>
          </tr>
     </table>
     <%= f.submit "SEND" ,class:"send-btn"%>
<% end %>

app/views/week_holiday_changes/_header.html.erb
<div class="second-header">
  <div class="left-header">
    <div class="header-title">
      <% if current_page?(controller: 'week_holiday_changes', action: 'index') %>
        <h2>週休変更一覧ページ</h2>
      <% elsif current_page?(controller: 'week_holiday_changes', action: 'new') %>
        <h2>週休変更申請ページ</h2>
      <% elsif current_page?(controller: 'week_holiday_changes', action: 'show') %>
        <h2>詳細ページ</h2>
      <% elsif current_page?(controller: 'week_holiday_changes', action: 'edit') %>
        <h2>週休変更の編集ページ</h2>
      <% end %>
    </div>
  </div>
  <div class="right-header">
    <div class="header-button">
      <%= link_to "グループ一覧", group_index_path %>
      <% if current_page?(controller: 'holidays', action: 'index') %>
            <%= link_to "週休変更申請", new_week_holiday_change_path(user_id: current_user.id) %>
            <%= link_to "週休変更一覧", week_holiday_changes_path(user_id: current_user.id) %>
      <% else %>
      <% end %>
      <%= link_to "有給休暇の申請", new_holiday_path %>
      <%= link_to "従業員一覧", users_path %>
    </div>
  </div>
</div>

app/views/week_holiday_changes/index.html.erb
<%= render partial: "header", locals: { user: @user } %>


<% @week_holidays.each do |f| %> 
  <%= link_to week_holiday_change_path(f.id), method: :get do %>
     <table class="request-table">
          <tr>
               <th class="detail-item"><%= "名前" %></th>
               <th class="detail-item"><%= "申請日" %></th>
               <th class="detail-item"><%= "週休日" %></th>
               <th class="detail-item"><%= "変更日" %></th>
               <th class="detail-item"><%= "リーダー" %></th>
               <th class="detail-item"><%= "部長" %></th>
               <th class="detail-item"><%= "総務" %></th>
          </tr>
          <div class="formats">
               <tr>
                  <td class="detail-value"><%= f.user.user_name %></td>
                  <td class="detail-value"><%= f.created_at.strftime('%Y/%m/%d') %></td>
                  <td class="detail-value"><%= "" %><%= f.original_leave.strftime('%Y/%m/%d') %>
                  <td class="detail-value"><%= f.changed_leave.strftime('%Y/%m/%d') %></td>
                  <% if WeekHCheck.exists?(week_holiday_change_id: f.id) %> 
                        <% if WeekHCheck.exists?(week_holiday_change_id: f.id, position: "リーダー") %>
                            <% check = WeekHCheck.find_by(week_holiday_change_id: f.id, position: "リーダー") %>
                            <% if check.yes_no == "yes" %>
                              <td class="detail-value"><span>✅</span><%= check.user.user_name %></td>
                            <% elsif check.yes_no == "no" %>
                              <td class="detail-value"><span>❌</span><%= check.user.user_name %></td>
                            <% end %>
                        <% else %>
                              <td class="detail-value"><span>--</span></td>
                        <% end %>
                        <% if WeekHCheck.exists?(week_holiday_change_id: f.id, position: "部長") %>
                            <% check = WeekHCheck.find_by(week_holiday_change_id: f.id, position: "部長") %>
                            <% if check.yes_no == "yes" %>
                              <td class="detail-value"><span>✅</span><%= check.user.user_name %></td>
                            <% elsif check.yes_no == "no" %>
                              <td class="detail-value"><span>❌</span><%= check.user.user_name %></td>
                            <% end %>
                        <% else %>
                              <td class="detail-value"><span>--</span></td>
                        <% end %>         
                        <% if WeekHCheck.exists?(week_holiday_change_id: f.id, position: "システム管理者") %>
                            <% check = WeekHCheck.find_by(week_holiday_change_id: f.id, position: "システム管理者") %>
                            <% if check.yes_no == "yes" %>
                              <td class="detail-value"><span>✅</span><%= check.user.user_name %></td>
                            <% elsif check.yes_no == "no" %>
                              <td class="detail-value"><span>❌</span><%= check.user.user_name %></td>
                            <% end %>
                        <% else %>
                              <td class="detail-value"><span>--</span></td>
                        <% end %> 
                  <% else %>
                      <td class="detail-value"><span>--</span></td>
                      <td class="detail-value"><span>--</span></td>
                      <td class="detail-value"><span>--</span></td>
                  <% end %>
               </tr>
          </div>
     </table>   
  <% end %>
<% end %>

app/views/week_holiday_changes/new.html.erb
<div class="container">
  <%= render partial: "header", local: true %>
  <%= render partial: "form", local: true %>
</div>

app/views/week_holiday_changes/show.html.erb
<%= render partial: "header", local: true %>
<table class="request-table">
    <tr>
          <th class="detail-item"><%= "名前" %></th>
          <th class="detail-item"><%= "申請日" %></th>
          <th class="detail-item"><%= "週休日" %></th>
          <th class="detail-item"><%= "変更日" %></th>
          <th class="detail-item"><%= "リーダー" %></th>
          <th class="detail-item"><%= "部長" %></th>
          <th class="detail-item"><%= "総務" %></th>
    </tr>
    <div class="formats">
          <tr>    
               <td class="detail-value"><%= @week_holiday.user.user_name %></td>
               <td class="detail-value"><%= @week_holiday.created_at.strftime('%Y/%m/%d') %></td>
               <td class="detail-value"><%= "" %><%= @week_holiday.original_leave.strftime('%Y/%m/%d') %>
               <td class="detail-value"><%= @week_holiday.changed_leave.strftime('%Y/%m/%d') %></td>
          

               <% if WeekHCheck.exists?(week_holiday_change_id: @week_holiday.id) %>
                    <% if WeekHCheck.exists?(week_holiday_change_id: @week_holiday.id, position: "リーダー") %>
                         <% check = WeekHCheck.find_by(week_holiday_change_id: @week_holiday.id, position: "リーダー") %>
                         <% if check.yes_no == "yes" %>
                                   <td class="detail-value"><span>✅</span><%= check.user.user_name %></td>
                         <% elsif check.yes_no == "no" %>
                                   <td class="detail-value"><span>❌</span><%= check.user.user_name %></td>
                         <% end %>
                    <% else %>
                         <td class="detail-value"><span>--</span></td>
                    <% end %>

                    <% if WeekHCheck.exists?(week_holiday_change_id: @week_holiday.id, position: "部長") %>
                         <% check = WeekHCheck.find_by(week_holiday_change_id: @week_holiday.id, position: "部長") %>
                         <% if check.yes_no == "yes" %>
                         <td class="detail-value"><span>✅</span><%= check.user.user_name %></td>
                         <% elsif check.yes_no == "no" %>
                         <td class="detail-value"><span>❌</span><%= check.user.user_name %></td>
                         <% end %>
                    <% else %>
                         <td class="detail-value"><span>--</span></td>
                    <% end %>         

                    <% if WeekHCheck.exists?(week_holiday_change_id: @week_holiday.id, position: "システム管理者") %>
                         <% check = WeekHCheck.find_by(week_holiday_change_id: @week_holiday.id, position: "システム管理者") %>
                         <% if check.yes_no == "yes" %>
                         <td class="detail-value"><span>✅</span><%= check.user.user_name %></td>
                         <% elsif check.yes_no == "no" %>
                         <td class="detail-value"><span>❌</span><%= check.user.user_name %></td>
                         <% end %>
                    <% else %>
                         <td class="detail-value"><span>--</span></td>
                    <% end %> 
               <% else %>
                    <td class="detail-value"><span>--</span></td>
                    <td class="detail-value"><span>--</span></td>
                    <td class="detail-value"><span>--</span></td>
               <% end %>  
          </tr>
    </div>
</table>

<div class="yes-no-btn">
      <%# <% unless @h.repuested_by?(current_user) %>  
      <% unless WeekHCheck.exists?(user_id: current_user.id, week_holiday_change_id: @week_holiday.id) %><!-- ログインしているユーザーがチェック機能（承認・否認）を使ってなければOK -->  
            <% if WeekHCheck.exists?(yes_no: "no", week_holiday_change_id: @week_holiday.id) %> <!-- 自分はリクエスト機能を使っていないが、既に否認（NO）されている場合の処理 -->
                  <% if @week_holiday.user_id == current_user.id %> <!-- 投稿した本人なら、編集・削除できる。 -->
                        <%= "否認されているので、削除・編集する事ができます。" %>
                        <td><%= link_to "編集して再度申請", edit_week_holiday_change_path(@week_holiday.id) %></td>
                        <td><%= link_to "削除", week_holiday_change_path(@week_holiday.id), method: :delete %></td> 
                  <% end %>
            <% else %>   
                  <% unless @week_holiday.user_id == current_user.id %>                 <!-- 自分はまだ承認していなくて、まだ否認もされていない場合。ログインユーザーのポジションが部長か総務のいずれか -->
                        <% if current_user.position == "役員" || current_user.position == "システム管理者" %>
                              <%# 役員と総務はグループに属していなくても承認できる。 %>
                              <%=button_to "承認", week_holiday_change_agreement_path(@week_holiday.id), method: :post %>   
                              <%=button_to "否認", week_holiday_change_rejected_path(@week_holiday.id), method: :post %>
                        <% elsif current_user.position.in?(['リーダー', '主任', '部長']) %>
                                    
                              <% if (@week_holiday.user.groups.ids - current_user.groups.ids).size < @week_holiday.user.groups.ids.size %>
                                    <%# リーダーの所属しているグループidが、申請者のグループidを含んでいればOK %>
                                    <%=button_to "承認", week_holiday_change_agreement_path(@week_holiday.id), method: :post %>   
                                    <%=button_to "否認", week_holiday_change_rejected_path(@week_holiday.id), method: :post %>
                              <% end %>
                        <% end %>
                  <% end %>
            <% end %>
      <% end %>
</div>