config/routes.rb
Rails.application.routes.draw do

  devise_for :users, :controllers => {
    :passwords => 'users/passwords'
  }

  devise_scope :user do
    get '/users/sign_out' => 'devise/sessions#destroy'
  end

  get "users/holiday" => "users#holiday"
  get "users/week_holiday_change" => "users#week_holiday_change"

  resources :users do
    resources :remaining_holiday, only:  [:new, :create, :edit, :update], shallow: true
    resources :notification, only:  [:create, :show, :destroy], shallow: true
  end
 
  root to: "holidays#index"

  resources :group do
    get 'change_holidays', to:'group#change_holidays'
    # resources :group_user, only:  [:show, :create, :destroy]

    get 'add_page' => 'group_user#show'
    post 'add_member' => 'group_user#create'
    # delete 'group_user/:id' => 'group_user#destroy'
  end

  # get "group/change_holidays_show" => "group#change_holidays_show"
  get "holidays/cancel_new" => "holidays#cancel_new"
  get "holidays/consecutive_holiday" => "holidays#consecutive_holiday"
  post "holidays/cancel_create" => "holidays#cancel_create"

  resources :holidays do
    resources :comments, only: [:create] 
    post 'agreement', to: 'request#agreement'
    post 'rejected', to: 'request#rejected'
  end
  

  resources :week_holiday_changes do
    post 'agreement', to: 'week_h_checks#agreement'
    post 'rejected', to: 'week_h_checks#rejected'
  end
end

app/models/user.rb
class User < ApplicationRecord
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         
  has_many :group_users, dependent: :destroy
  has_many :groups, through: :group_users
  has_many :requests, dependent: :destroy
  has_many :holidays , dependent: :destroy
  has_one  :remaining_holiday, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :Notifications, dependent: :destroy
  has_many :WeekHolidayChanges, dependent: :destroy
  has_many :week_h_checks, dependent: :destroy
  # has_many :groups, through: :Notifications

  # PASSWORD_REGEX = /\A(?=.*?[a-z])(?=.*?\d)[a-z\d]+\z/i.freeze

  # with_options presence: true, format: { with: PASSWORD_REGEX, message: 'には英字と数字の両方を含めて設定してください' }, length: { minimum: 6 },
  #     confirmation: true do
  #   validates :password
  #   validates :password_confirmation
  # end

  with_options presence: true do
    validates :email
    validates :user_name
    validates :position
    # validates :encrypted_password
  end
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  def new
    super
  end

  # POST /resource/password
  def create
    super
  end

  # GET /resource/password/edit?reset_password_token=abcdef
  def edit
    super
  end

  # PUT /resource/password
  def update
    super
  end

  protected

  def after_resetting_password_path_for(resource)
    super(resource)
  end

  # The path used after sending reset password instructions
  def after_sending_reset_password_instructions_path_for(resource_name)
    super(resource_name)
  end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true
class Users::RegistrationsController < Devise::RegistrationsController
  before_action :configure_sign_up_params, only: [:create]
  before_action :configure_account_update_params, only: [:update]
  before_action :set_user

  # GET /resource/sign_up
  def new
    super

    puts '========================='
    puts 'GET /resource/sign_up'
    puts '========================='
  end

  # POST /resource
  def create
    super
  end

  # GET /resource/edit
  def edit
    super

    puts '========================='
    puts 'GET /resource/edit'
    puts '========================='
  end

  # PUT /resource
  def update
    super
  end

  # DELETE /resource
  def destroy
    super
  end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # 通常はサインイン後に
  # 期限切れになるセッションデータを強制的に今すぐ期限切れにします。
  # これは、ユーザーがすべての OAuth セッションデータを削除して、
  # 途中で oauth サインイン/アップをキャンセルしたい場合に便利です。
  def cancel
    super
  end

  protected

  # If you have extra params to permit, append them to the sanitizer.
  def configure_sign_up_params
    devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  end

  # If you have extra params to permit, append them to the sanitizer.
  def configure_account_update_params
    devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  end

  # The path used after sign up.
  def after_sign_up_path_for(resource)
    super(resource)
  end

  # The path used after sign up for inactive accounts.
  def after_inactive_sign_up_path_for(resource)
    super(resource)
  end


  private
  # ストロングパラメータ
  def set_user
    # @user = User.find(params[:id])
  end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  # before_action :set_user, only: [:show, ]
  # before_action :set_week_holiday_changes, only: [:show, ]
  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
    @r = @user.remaining_holiday  
    @holidays = @user.holidays
    @groups = Group.all
    # @week_holidays = @user.WeekHolidayChanges.find_by(params[user_id: @user.id])
    @week_holidays = WeekHolidayChange.all
  end

  def holiday
    @users = User.all
    @holidays = Holiday.all.order(updated_at: :desc).page(params[:page]).per(10)
  end

  def week_holiday_change
    @users = User.all
    @changes = WeekHolidayChange.all.order(created_at: :desc).page(params[:page]).per(10)
  end


  def create 
    @notification = Notification.new
    @group = Group.find(params[:group_id]) 
    @user = User.find(params[:user_id]) 
    @notification.user_id = @user
    @notification.group_id = @group
    if @group.save
         redirect_to group_user_path(group_id: @group.id, id: @group.id)
         # 将来的には、JavaScriptで非同期通信にしたい
    else
         render :new
    end
  end

  def edit
    @user = User.find(params[:id]) 
  end

  def update
    @user = User.find(params[:id]) 
    @user.update(user_params) 
    # @copy_user = 
    # user_params
    redirect_to :root
  end    

  def destroy
    @user = User.find(params[:id]) 
    @user.destroy
    redirect_to :root
  end

  private
  # ストロングパラメータ
  def set_user
    @user = User.find(params[:id])
  end

  def user_params
    params.require(:user).permit(:email, :user_name, :position)
    # @user.user_name = 
  end
end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_header.html.erb
<div class="second-header">
  <div class="left-header">
    <div class="header-title">
      <% if current_page?(controller: 'users', action: 'index') %>
        <h2>従業員一覧</h2>
      <% elsif current_page?(controller: 'users', action: 'holiday') %>
        <h2>全社員の有給申請一覧</h2>
      <% elsif current_page?(controller: 'users', action: 'week_holiday_change') %>
        <h2>週休変更申請一覧</h2>
      <% else %>
        <h2>詳細ページ</h2>
      <% end %>
    </div>
  </div>
  <div class="right-header">
    <div class="header-button">
      <%= link_to "グループ一覧", group_index_path %>
      <%= link_to "有給申請一覧", users_holiday_path %>
      <% unless current_page?(controller: 'users', action: 'week_holiday_change') %>
        <%= link_to "週休休暇一覧", users_week_holiday_change_path %>        
      <% end %>  
      
     <% if current_page?(controller: 'users', action: 'index') %>
        <%= link_to "新規グループ作成", new_group_path %>
     <% else %>
          <%= link_to "従業員一覧", users_path %>
     <% end %>
    </div>
  </div>
</div>

app/views/users/edit.html.erb
<%# <%= render partial: "header", locals: { user: @user } %>
<div class='form-wrap'>
  <%# <%= render "users/shared/error_messages", resource: @user %>
    <div class="header">
      <div class="form-header-text">
        <h1>基本情報の編集画面</h1>
      </div>
    </div>
  <%= form_with model: @user, url:user_path(@user.id), method: :patch do |f| %>
  <%# <%= form_with scope: :@user, url:user_path(@user.id), method: :patch, local: true do |f| %>
    <div class="form-group">
      <div class='form-text-wrap'>
        <label class="form-text">名前</label>
        <%= f.text_area :user_name, autofocus: true, class:"input-default", id:"user_name", maxlength:"20" %>
      </div>

      <div class='form-text-wrap'>
        <label class="form-text">メールアドレス</label>
        <%= f.email_field :email, class:"input-default", id:"email", placeholder:"会社用のメールアドレス", autofocus: true %>
      </div>
      

      <%# <div class='form-text-wrap'>
        <label class="form-text">パスワード</label>
        <%= f.password_field :password, class:"input-default", id:"password", placeholder:"6文字以上の半角英数字" %>
      <%# </div> %>

          

      <div class='form-text-wrap'>
        <label class="form-text">役職</label>
        <%= f.select :position, ['一般社員', 'リーダー', '主任', '部長', '役員', 'システム管理者'], {include_blank: '---'} %>
      </div>
    
      <div class='register-btn'>
        <%= f.submit "アップデート" %>
      </div>
    </div>
  <% end %>
    <div class="form-group">
      <div class='register-btn'>
        <%= button_to "アカウントの削除", user_path(@user.id), data: { confirm: "本当にこのアカウントを削除しますか?" }, method: :delete %>
      </div>
    </div>

  
</div>

app/views/users/holiday.html.erb
<%= render partial: "header", locals: { user: @user } %>


  <div class='item-info'>   
    <% if @holidays.exists? %> 
      <% @holidays.each do |f| %>
        <%= link_to holiday_path(f.id), method: :get do %>
          <table class="request-table">
              <tr>
                  <th class="detail-item"><%= "名前" %></th>
                  <th class="detail-item"><%= "申請日" %></th>
                  <th class="detail-item"><%= "取得日" %></th>
                  <th class="detail-item"><%= "日/時" %></th>
                  <th class="detail-item"><%= "時間休・内訳" %></th>
                  <th class="detail-item"><%= "時間休・合計" %></th>
                  <th class="detail-item"><%= "事由" %></th>
                  <th class="detail-item"><%= "リーダー" %></th>
                  <th class="detail-item"><%= "部長" %></th>
                  <th class="detail-item"><%= "総務" %></th>
              </tr>
            <div class="formats">
              <tr>
                <td class="detail-value"><%= f.user.user_name %></td>
                <td class="detail-value"><%= f.updated_at.strftime('%Y/%m/%d') %></td>
                <td class="detail-value"><%= "" %><%= f.application_date.strftime('%Y/%m/%d') %>
                <td class="detail-value"><%= f.acquisition_days %></td>
                <% if f.holiday_time_start.nil? %> 
                      <td class="detail-value"><span>時間の指定なし</span></td>
                <% else %>
                      <td class="detail-value"><%= f.holiday_time_start.strftime('%H') %>
                                          <%= "〜" %><%= f.holiday_time_end.strftime( "%H" ) %></td>
                <% end %> 
                <td class="detail-value"><%= f.acquisition_time %>時間</td>
                <td class="detail-value"><%= f.reason %></td>
                  <% if Request.exists?(holiday_id: f.id) %> 
                        <% if Request.exists?(holiday_id: f.id, position: "リーダー") %>
                            <% request = Request.find_by(holiday_id: f.id, position: "リーダー") %>
                            <% if request.yes_no == "yes" %>
                              <td class="detail-value"><span>✅</span><%= request.user.user_name %></td>
                            <% elsif request.yes_no == "no" %>
                              <td class="detail-value"><span>❌</span><%= request.user.user_name %></td>
                            <% end %>
                        <% else %>
                              <td class="detail-value"><span>--</span></td>
                        <% end %>
                        <% if Request.exists?(holiday_id: f.id, position: "部長") %>
                            <% request = Request.find_by(holiday_id: f.id, position: "部長") %>
                            <% if request.yes_no == "yes" %>
                              <td class="detail-value"><span>✅</span><%= request.user.user_name %></td>
                            <% elsif request.yes_no == "no" %>
                              <td class="detail-value"><span>❌</span><%= request.user.user_name %></td>
                            <% end %>
                        <% else %>
                              <td class="detail-value"><span>--</span></td>
                        <% end %>         
                        <% if Request.exists?(holiday_id: f.id, position: "システム管理者") %>
                            <% request = Request.find_by(holiday_id: f.id, position: "システム管理者") %>
                            <% if request.yes_no == "yes" %>
                              <td class="detail-value"><span>✅</span><%= request.user.user_name %></td>
                            <% elsif request.yes_no == "no" %>
                              <td class="detail-value"><span>❌</span><%= request.user.user_name %></td>
                            <% end %>
                        <% else %>
                              <td class="detail-value"><span>--</span></td>
                        <% end %> 
                  <% else %>
                      <td class="detail-value"><span>--</span></td>
                      <td class="detail-value"><span>--</span></td>
                      <td class="detail-value"><span>--</span></td>
                  <% end %>
                </tr>
            </div>
          </table>
        <% end %>
      <% end %>
      <div class="content-title"><%= paginate @holidays %></div>
    <% else %>
        <div class='menber_name'>
          <span>有給休暇の申請はまだありません</span>
        </div>
    <% end %>       
  </div>

app/views/users/index.html.erb
<%= render partial: "header", locals: { user: @user } %>


  
  <% @users.each do |user| %>
    <div class='flex-employee-list'>
        <div class="users-user-name">
          <li> <%= user.user_name %>さん</li>
        </div>

      <% if RemainingHoliday.exists?(user_id: user.id) %> 
            <div class="users-contents"><li><%= link_to "詳細ページ", user_path(user.id) %></li></div>
      <% else %>
            <div class="users-contents"><li><%= link_to "有給休暇の付与", new_user_remaining_holiday_path(user_id: user.id) %></div>
      <% end %>   
      <div class="users-contents"><li><%= link_to "基本情報の編集", edit_user_path(user.id) %></li></div>
    </div>
  <% end %>
  

app/views/users/show.html.erb
<%= render partial: "header", locals: { user: @user } %>

        
<div class="r-holiday">
     <h2> <%= @user.user_name %>さん</h2>
</div>



<div class="changeable-holiday">
          <h3>今年度付与分の有給休暇<%= @r.total_days %>日と<%= @r.total_time %>時間(申請分を差し引く前)</h3>
          <div class="r-holiday-btn">
               <%= button_to "付与した有給の編集", edit_remaining_holiday_path(user_id: @user.id), method: :get %>
          </div>
</div>

<div class="changeable-holiday">
          <h3> 残り  <%= @r.changeable_days %>日と<%= @r.changeable_time %>時間  (申請分を差し引いた取得可能時間)</h3> 
</div>

<div class="changeable-holiday">
     <div class="content-title">
               <h3>申請した有給休暇</h3> 
     </div>

     <% if @holidays.exists? %> 
          <% @holidays.each do |f| %> 
               <%= link_to holiday_path(f.id), method: :get do %>
                    <table class="request-table">
                         <tr>
                              <th class="detail-item"><%= "申請日" %></th>
                              <th class="detail-item"><%= "取得日" %></th>
                              <th class="detail-item"><%= "取得日数" %></th>
                              <th class="detail-item"><%= "時〜時" %></th>
                              <th class="detail-item"><%= "取得時間" %></th>
                              <th class="detail-item"><%= "事由" %></th>
                              <th class="detail-item"><%= "残日数" %></th> 
                              <th class="detail-item"><%= "残時間" %></th> 
                         </tr>
                         <div class="formats">
                              <tr>
                                   <td class="detail-value"><%= f.created_at.strftime('%Y/%m/%d') %></td>
                                   <td class="detail-value"><%= "" %><%= f.application_date.strftime('%Y/%m/%d') %>
                                   <td class="detail-value"><%= f.acquisition_days %></td>
                                   <% if f.holiday_time_start.nil? %> 
                                        <td class="detail-value"><span>ーー</span></td>
                                   <% else %>
                                        <td class="detail-value"><%= "start " %><%= f.holiday_time_start.strftime('%H') %>
                                                            <%= "〜end " %><%= f.holiday_time_end.strftime( "%H" ) %></td>
                                   <% end %> 
                                   <% if f.acquisition_time.nil? %> 
                                        <td class="detail-value"><span>ーー</span></td>
                                   <% else %>
                                        <td class="detail-value"><%= "start " %><%= f.acquisition_time %>時間</td>
                                   <% end %>
                                   <td class="detail-value"><%= f.reason %></td>
                                   <td class="detail-value"><%= f.day_record  %>日</td>
                                   <td class="detail-value"><%= f.time_record %>時間</td>
                              </tr>
                         </div>
                    </table>   
               <% end %>
          <% end %>
     <% else %>
          <div class="r-holiday">
               <li>有給休暇の申請はまだありません</li>
          </div>
     <% end %>  
 </div>

<div class="changeable-holiday">
     <div class="content-title">
               <h3>申請した週休の変更</h3> 
     </div>

     <ul class='item-contents'>
          <div class='item-info'>   
               <% if @week_holidays.exists? %> 
                    <% @week_holidays.each do |f| %>
                         <% if WeekHolidayChange.where(id: f.id, user_id: @user.id).exists?%>
                              <%= link_to week_holiday_change_path(f.id), method: :get do %>
                                   <table class="request-table">
                                        <tr>
                                             <th class="detail-item"><%= "名前" %></th>
                                             <th class="detail-item"><%= "申請日" %></th>
                                             <th class="detail-item"><%= "週休日" %></th>
                                             <th class="detail-item"><%= "変更日" %></th>
                                             <th class="detail-item"><%= "リーダー" %></th>
                                             <th class="detail-item"><%= "部長" %></th>
                                             <th class="detail-item"><%= "総務" %></th>
                                        </tr>
                                        <div class="formats">
                                             <tr>    
                                                  <td class="detail-value"><%= f.user.user_name %></td>
                                                  <td class="detail-value"><%= f.created_at.strftime('%Y/%m/%d') %></td>
                                                  <td class="detail-value"><%= "" %><%= f.original_leave.strftime('%Y/%m/%d') %>
                                                  <td class="detail-value"><%= f.changed_leave.strftime('%Y/%m/%d') %></td>
                                             

                                                  <% if WeekHCheck.exists?(week_holiday_change_id: f.id) %>
                                                       <% if WeekHCheck.exists?(week_holiday_change_id: f.id, position: "リーダー") %>
                                                            <% check = WeekHCheck.find_by(week_holiday_change_id: f.id, position: "リーダー") %>
                                                            <% if check.yes_no == "yes" %>
                                                                      <td class="detail-value"><span>✅</span><%= check.user.user_name %></td>
                                                            <% elsif check.yes_no == "no" %>
                                                                      <td class="detail-value"><span>❌</span><%= check.user.user_name %></td>
                                                            <% end %>
                                                       <% else %>
                                                            <td class="detail-value"><span>--</span></td>
                                                       <% end %>

                                                       <% if WeekHCheck.exists?(week_holiday_change_id: f.id, position: "部長") %>
                                                            <% check = WeekHCheck.find_by(week_holiday_change_id: f.id, position: "部長") %>
                                                            <% if check.yes_no == "yes" %>
                                                            <td class="detail-value"><span>✅</span><%= check.user.user_name %></td>
                                                            <% elsif check.yes_no == "no" %>
                                                            <td class="detail-value"><span>❌</span><%= check.user.user_name %></td>
                                                            <% end %>
                                                       <% else %>
                                                            <td class="detail-value"><span>--</span></td>
                                                       <% end %>         

                                                       <% if WeekHCheck.exists?(week_holiday_change_id: f.id, position: "システム管理者") %>
                                                            <% check = WeekHCheck.find_by(week_holiday_change_id: f.id, position: "システム管理者") %>
                                                            <% if check.yes_no == "yes" %>
                                                            <td class="detail-value"><span>✅</span><%= check.user.user_name %></td>
                                                            <% elsif check.yes_no == "no" %>
                                                            <td class="detail-value"><span>❌</span><%= check.user.user_name %></td>
                                                            <% end %>
                                                       <% else %>
                                                            <td class="detail-value"><span>--</span></td>
                                                       <% end %> 
                                                  <% else %>
                                                       <td class="detail-value"><span>--</span></td>
                                                       <td class="detail-value"><span>--</span></td>
                                                       <td class="detail-value"><span>--</span></td>
                                                  <% end %>  
                                             </tr>
                                        </div>
                                   </table>
                              <% end %>
                         <% end %>
                    <% end %>
               <% else %>
                    <div class='menber_name'>
                         <li>週休の変更申請はまだありません</li>
                    </div>
               <% end %>     
          </div>
     </ul>
</div>

app/views/users/week_holiday_change.html.erb
<%= render partial: "header", locals: { user: @user } %>


<div class='item-info'>   
     <% if @changes.exists? %> 
          <% @changes.each do |f| %>
               <%= link_to week_holiday_change_path(f.id), method: :get do %>
                    <table class="request-table">
                         <tr>
                              <th class="detail-item"><%= "名前" %></th>
                              <th class="detail-item"><%= "申請日" %></th>
                              <th class="detail-item"><%= "週休日" %></th>
                              <th class="detail-item"><%= "変更日" %></th>
                              <th class="detail-item"><%= "リーダー" %></th>
                              <th class="detail-item"><%= "部長" %></th>
                              <th class="detail-item"><%= "総務" %></th>
                         </tr>
                         <div class="formats">
                              <tr>    
                                   <td class="detail-value"><%= f.user.user_name %></td>
                                   <td class="detail-value"><%= f.created_at.strftime('%Y/%m/%d') %></td>
                                   <td class="detail-value"><%= "" %><%= f.original_leave.strftime('%Y/%m/%d') %>
                                   <td class="detail-value"><%= f.changed_leave.strftime('%Y/%m/%d') %></td>
                              

                                   <% if WeekHCheck.exists?(week_holiday_change_id: f.id) %>
                                        <% if WeekHCheck.exists?(week_holiday_change_id: f.id, position: "リーダー") %>
                                             <% check = WeekHCheck.find_by(week_holiday_change_id: f.id, position: "リーダー") %>
                                             <% if check.yes_no == "yes" %>
                                                       <td class="detail-value"><span>✅</span><%= check.user.user_name %></td>
                                             <% elsif check.yes_no == "no" %>
                                                       <td class="detail-value"><span>❌</span><%= check.user.user_name %></td>
                                             <% end %>
                                        <% else %>
                                             <td class="detail-value"><span>--</span></td>
                                        <% end %>

                                        <% if WeekHCheck.exists?(week_holiday_change_id: f.id, position: "部長") %>
                                             <% check = WeekHCheck.find_by(week_holiday_change_id: f.id, position: "部長") %>
                                             <% if check.yes_no == "yes" %>
                                             <td class="detail-value"><span>✅</span><%= check.user.user_name %></td>
                                             <% elsif check.yes_no == "no" %>
                                             <td class="detail-value"><span>❌</span><%= check.user.user_name %></td>
                                             <% end %>
                                        <% else %>
                                             <td class="detail-value"><span>--</span></td>
                                        <% end %>         

                                        <% if WeekHCheck.exists?(week_holiday_change_id: f.id, position: "システム管理者") %>
                                             <% check = WeekHCheck.find_by(week_holiday_change_id: f.id, position: "システム管理者") %>
                                             <% if check.yes_no == "yes" %>
                                             <td class="detail-value"><span>✅</span><%= check.user.user_name %></td>
                                             <% elsif check.yes_no == "no" %>
                                             <td class="detail-value"><span>❌</span><%= check.user.user_name %></td>
                                             <% end %>
                                        <% else %>
                                             <td class="detail-value"><span>--</span></td>
                                        <% end %> 
                                   <% else %>
                                        <td class="detail-value"><span>--</span></td>
                                        <td class="detail-value"><span>--</span></td>
                                        <td class="detail-value"><span>--</span></td>
                                   <% end %>  
                              </tr>
                         </div>
                    </table>
               <% end %>
          <% end %>
          <div class="content-title"><%= paginate @changes %></div>
     <% else %>
          <div class='menber_name'>
               <span>有給休暇の申請はまだありません</span>
          </div>
     <% end %>       
</div>