config/routes.rb
Rails.application.routes.draw do

  devise_for :users, :controllers => {
    :passwords => 'users/passwords'
  }

  devise_scope :user do
    get '/users/sign_out' => 'devise/sessions#destroy'
  end

  get "users/holiday" => "users#holiday"
  get "users/week_holiday_change" => "users#week_holiday_change"

  resources :users do
    resources :remaining_holiday, only:  [:new, :create, :edit, :update], shallow: true
    resources :notification, only:  [:create, :show, :destroy], shallow: true
  end
 
  root to: "holidays#index"

  resources :group do
    get 'change_holidays', to:'group#change_holidays'
    # resources :group_user, only:  [:show, :create, :destroy]

    get 'add_page' => 'group_user#show'
    post 'add_member' => 'group_user#create'
    # delete 'group_user/:id' => 'group_user#destroy'
  end

  # get "group/change_holidays_show" => "group#change_holidays_show"
  get "holidays/cancel_new" => "holidays#cancel_new"
  get "holidays/consecutive_holiday" => "holidays#consecutive_holiday"
  post "holidays/cancel_create" => "holidays#cancel_create"

  resources :holidays do
    resources :comments, only: [:create] 
    post 'agreement', to: 'request#agreement'
    post 'rejected', to: 'request#rejected'
  end
  

  resources :week_holiday_changes do
    post 'agreement', to: 'week_h_checks#agreement'
    post 'rejected', to: 'week_h_checks#rejected'
  end
end

app/models/group.rb
class Group < ApplicationRecord
     has_many :group_users
     has_many :notifications
     has_many :users, through: :group_users, dependent: :destroy
     accepts_nested_attributes_for :group_users
     # has_many :users, through: :notifications
     validates :group_name, presence: true, uniqueness: true


     has_many :group_holidays, through: :users, source: :holiday 

     def yes_no?
          requests.where(yes_no: "no").exists?
     end
end

app/models/user.rb
class User < ApplicationRecord
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         
  has_many :group_users, dependent: :destroy
  has_many :groups, through: :group_users
  has_many :requests, dependent: :destroy
  has_many :holidays , dependent: :destroy
  has_one  :remaining_holiday, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :Notifications, dependent: :destroy
  has_many :WeekHolidayChanges, dependent: :destroy
  has_many :week_h_checks, dependent: :destroy
  # has_many :groups, through: :Notifications

  # PASSWORD_REGEX = /\A(?=.*?[a-z])(?=.*?\d)[a-z\d]+\z/i.freeze

  # with_options presence: true, format: { with: PASSWORD_REGEX, message: 'には英字と数字の両方を含めて設定してください' }, length: { minimum: 6 },
  #     confirmation: true do
  #   validates :password
  #   validates :password_confirmation
  # end

  with_options presence: true do
    validates :email
    validates :user_name
    validates :position
    # validates :encrypted_password
  end
end

app/controllers/group_controller.rb
class GroupController < ApplicationController
     before_action :authenticate_user!
     before_action :set_group, only: [:edit, :show, :update, :destroy]
     protect_from_forgery :except => [:destroy]
     # , :change_holidays_show

     def index
          @groups = Group.all
          # .order(created_at: :desc)
          @user = User.find_by(id: current_user.id)
          @my_groups = GroupUser.where(user_id: current_user.id)
     end

     def new
          @group = Group.new
     end

     def create
          @group = Group.new(group_params)
          if @group.save
               redirect_to root_path
          else
               render :new
          end
     end

     def show
          member_id = @group.users.ids
          @group_holidays = Holiday.where(user_id: member_id).order(updated_at: :desc).page(params[:page]).per(10)
     end

     def change_holidays
          @group = Group.find(params[:group_id])
          member_id = @group.users.ids
          @group_change_holidays = WeekHolidayChange.where(user_id: member_id).order(updated_at: :desc).page(params[:page]).per(10)
     end

     def edit
          @group = Group.find(params[:id])
     end
          
     def update
          @group = Group.find(params[:id])
          if @group.update(group_params)
               redirect_to root_path
          else
               render :edit
          end
     end  

     def group_user
          @group = Group.find(params[:group_id])
          @user = User.all
     end

     def group_join 
          @group = Group.find(params[:group_id]) 
          @user = User.find(params[:user_id]) 
          @group.users << @user
          if @group.save
               redirect_to group_user_path(group_id: @group.id, id: @group.id)
               # redirect_to group_user_path(group_id: @group.id, id: @group.id)
               # 将来的には、JavaScriptで非同期通信にしたい
          else
               render :show
          end
     end

     def destroy
          group = Group.find(params[:id])
          group.destroy
          redirect_to :root
     end




     private
     # ストロングパラメータ
     def group_params    
          params.require(:group).permit(:group_name)
     end

     def set_group
          @group = Group.find(params[:id])
     end

end

app/helpers/group_helper.rb
module GroupHelper
end

app/views/group/_form.html.erb
     <div class=container4>
          <%= f.text_area :group_name, class:"items-text", id:"group-name", placeholder:"グループ名を入力してください", maxlength:"20" %>
          <div class="submit-btn"><%= f.submit "作成" %></div>
     </div>

app/views/group/_header.html.erb
<div class="second-header">
     <div class="left-header">
          <div class="header-title">
               <% if current_page?(controller: 'group', action: 'index') %>
                    <h1>グループ一覧</h1>
               <% elsif current_page?(controller: 'group', action: 'new') %>
                    <h1>グループ作成ページ</h1>
               <% elsif current_page?(controller: 'group', action: 'show') %>
                    <h1>グループの有給休暇申請一覧</h1>
               <% elsif current_page?(controller: 'group', action: 'edit') %>
                    <h1>グループ情報の編集</h1>
               <% elsif current_page?(controller: 'group_user', action: 'add_page') %>
                    <h1>グループメンバーの追加</h1>
               <% end %>
          </div>
     </div>
     <div class="right-header">
          <div class="header-button">
               <% unless current_page?(controller: 'group', action: 'index') %>
                    <%= link_to "グループ一覧", group_index_path %>
               <% end %>
               
               <% unless current_user.position == "一般社員"  %>
                    <%= link_to "従業員一覧", users_path %>
                    <%= link_to "有給申請一覧", users_holiday_path %>
                    <%= link_to "週休休暇一覧", users_week_holiday_change_path %>
               <% end %>
               <% if current_user.position == "システム管理者"  %>
                    
                    <% unless current_page?(controller: 'group', action: 'new') %>
                         <%= link_to "新規グループ作成", new_group_path %>
                    <% end %>
               <% end %>
          </div>
     </div>
</div>

app/views/group/change_holidays.html.erb
<%# <%= render partial: "header", locals: { user: @user } %>
<div class="second-header">
     <div class="left-header">
          <div class="header-title">
                    <h1>グループの週休変更申請一覧</h1>
          </div>
     </div>
     <div class="right-header">
          <div class="header-button">
     
               
               <% unless current_user.position == "一般社員"  %>
                    <%= link_to "従業員一覧", users_path %>
                    <%= link_to "有給申請一覧", users_holiday_path %>
                    <%= link_to "週休休暇一覧", users_week_holiday_change_path %>
               <% end %>
               <% if current_user.position == "システム管理者"  %>
                    
                    <% unless current_page?(controller: 'group', action: 'new') %>
                         <%= link_to "新規グループ作成", new_group_path %>
                    <% end %>
               <% end %>
          </div>
     </div>
</div>

  <div class='group-info'>
     <h1 class='group-name'>
          <%= @group.group_name %>
     </h1>
     <h3 class="group-member">
          <% if @group.users.exists? %> 
               <% @group.users.each do |f| %>
               <%= f.user_name %>
               <% end %>
          <% else %>
               <div class='menber_name'>
               <span>グループメンバーがいません</span>
               </div>
          <% end %>
     </h3>
  </div>

<ul class='item-contents'>
  <div class='item-info'>   
     <% if @group_change_holidays.exists? %> 
          <div class="content-title"><%= paginate @group_change_holidays %></div>
          <% @group_change_holidays.each do |f| %>
               <%= link_to week_holiday_change_path(f.id), method: :get do %>
                    <table class="request-table">
                         <tr>
                              <th class="detail-item"><%= "名前" %></th>
                              <th class="detail-item"><%= "申請日" %></th>
                              <th class="detail-item"><%= "週休日" %></th>
                              <th class="detail-item"><%= "変更日" %></th>
                              <th class="detail-item"><%= "リーダー" %></th>
                              <th class="detail-item"><%= "部長" %></th>
                              <th class="detail-item"><%= "総務" %></th>
                         </tr>
                         <div class="formats">
                              <tr>
                    <td class="detail-value"><%= f.user.user_name %></td>
                    <td class="detail-value"><%= f.created_at.strftime('%Y/%m/%d') %></td>
                    <td class="detail-value"><%= "" %><%= f.original_leave.strftime('%Y/%m/%d') %>
                    <td class="detail-value"><%= f.changed_leave.strftime('%Y/%m/%d') %></td>
                    <% if WeekHCheck.exists?(week_holiday_change_id: f.id) %> 
                         <% if WeekHCheck.exists?(week_holiday_change_id: f.id, position: "リーダー") %>
                              <% check = WeekHCheck.find_by(week_holiday_change_id: f.id, position: "リーダー") %>
                              <% if check.yes_no == "yes" %>
                                   <td class="detail-value"><span>✅</span><%= check.user.user_name %></td>
                              <% elsif check.yes_no == "no" %>
                                   <td class="detail-value"><span>❌</span><%= check.user.user_name %></td>
                              <% end %>
                         <% else %>
                                   <td class="detail-value"><span>--</span></td>
                         <% end %>
                         <% if WeekHCheck.exists?(week_holiday_change_id: f.id, position: "部長") %>
                              <% check = WeekHCheck.find_by(week_holiday_change_id: f.id, position: "部長") %>
                              <% if check.yes_no == "yes" %>
                                   <td class="detail-value"><span>✅</span><%= check.user.user_name %></td>
                              <% elsif check.yes_no == "no" %>
                                   <td class="detail-value"><span>❌</span><%= check.user.user_name %></td>
                              <% end %>
                         <% else %>
                                   <td class="detail-value"><span>--</span></td>
                         <% end %>         
                         <% if WeekHCheck.exists?(week_holiday_change_id: f.id, position: "システム管理者") %>
                              <% check = WeekHCheck.find_by(week_holiday_change_id: f.id, position: "システム管理者") %>
                              <% if check.yes_no == "yes" %>
                                   <td class="detail-value"><span>✅</span><%= check.user.user_name %></td>
                              <% elsif check.yes_no == "no" %>
                                   <td class="detail-value"><span>❌</span><%= check.user.user_name %></td>
                              <% end %>
                         <% else %>
                                   <td class="detail-value"><span>--</span></td>
                         <% end %> 
                    <% else %>
                         <td class="detail-value"><span>--</span></td>
                         <td class="detail-value"><span>--</span></td>
                         <td class="detail-value"><span>--</span></td>
                    <% end %>
                    </tr>
                         </div>
                    </table>
               <% end %>
          <% end %>
          <div class="content-title"><%= paginate @group_change_holidays %></div>
     <% else %>
          <div class='group-member'>
               <h2>有給休暇の申請はまだありません</h29>
          </div>
     <% end %>       
  </div>
</ul>

app/views/group/edit.html.erb
<%= render partial: 'group/header' %>
<div class="item-show">
    <div class="edit-group">
     <h1><%= @group.group_name%></h1>
    </div>
  
  <div class="item-box">

    <div class="edit-form">
      <h3>グループの名前の変更</h3>
      <%= form_with model: @group, local: true do |f| %> 
        <%= render :partial => 'form', :locals => {:f => f, :edit_flag => true} %>
      <% end %>
    </div>

    <div class='add-group'>
      <%= button_to "グループメンバーの追加", group_add_page_path(group_id: @group.id), method: :get %>
    </div>
    <div class="delete-btn">
      <%= button_to 'グループを消去する', group_path(@group.id), data: { confirm: '削除しますか？' }, method: :delete %>
    </div>

  </div>
</div>

app/views/group/index.html.erb
<%= render partial: "header", locals: { user: @user } %>

<div class='main'>
  <ul class='item-lists'>
    <% @groups.each do |group| %>
      <h2 class='item-name'><%=  group.group_name%>
      </h2>
      <h2 class='item-name'>
        <% if @user.position.in?(['リーダー', '主任', '部長', '役員', 'システム管理者']) %> <!-- ログインユーザーのポジションが三つの中に含まれているかどうか -->
          <% if group.users.exists? %>                         <!-- グループにユーザーが存在するかどうか -->
            
            <% if Holiday.where(user_id: group.users.ids).exists? %><!-- グループのユーザーの申請した有給があるかどうか -->
              <% @group_holidays = Holiday.where(user_id: group.users.ids) %>
                <% i = 0 %>
                <% @group_holidays.each do |request_holiday| %><!-- グループの有給申請を一つずつ精査していく -->
                  <% unless Request.where(holiday_id: request_holiday.id, yes_no: "no").exists? %>  <!-- 既に否認されているものでなければOK -->
                    <% unless Request.where(holiday_id: request_holiday.id, user_id: @user.id).exists? || request_holiday.user == current_user%>
                      <!-- ↑既にログインユーザーが承認していない。もしくは、申請したのがログインユーザーでなければOK -->
                      <% if current_user.position == "システム管理者" %><!-- ログインユーザーのpositionがシステム管理者の場合 -->
                        <% i += 1 %>
                      <% else %>
                        <% if  current_user.groups.present? %><!-- ログインユーザーが現在グループに所属している場合 --> 
                          <% if current_user.group_ids.include?(group.id) %>
                            <% i += 1 %>
                          <% end %>
                        <% end  %>
                      <% end %>
                    <% end %>
                  <% end %>
                <% end %>
                <% if i > 0 %>
                  <%= "🔔" %><%= i %><%= "件 未承認の有給申請があります" %>
                <% else %>
                  <%= "承認待ちの申請はありません" %>
                <% end %>
            <% else %>
              <%= "申請はまだありません" %>
            <% end %>
            <div class='week_holiday_notice'>
              <% if WeekHolidayChange.where(user_id: group.users.ids).exists? %><!-- グループのユーザーの申請した有給があるかどうか -->
                <% @group_week_h_changes = WeekHolidayChange.where(user_id: group.users.ids) %>
                  <% i = 0 %>
                  <% @group_week_h_changes.each do |week_holiday| %><!-- グループの週休申請を一つずつ精査していく -->
                    <% unless WeekHCheck.where(week_holiday_change_id: week_holiday.id, yes_no: "no").exists? %>  <!-- 既に否認されているものでなければOK -->
                      <% unless WeekHCheck.where(week_holiday_change_id: week_holiday.id, user_id: @user.id).exists? || week_holiday.user == current_user%>
                        <!-- ↑既にログインユーザーが承認していない。もしくは、申請したのがログインユーザーでなければOK -->
                        <% if current_user.position == "システム管理者" %><!-- ログインユーザーのpositionがシステム管理者の場合 -->
                          <% i += 1 %>
                        <% else %>
                          <% if  current_user.groups.present? %><!-- ログインユーザーが現在グループに所属している場合 --> 
                            <% if current_user.group_ids.include?(group.id) %>
                              <% i += 1 %>
                            <% end %>
                          <% end  %>
                        <% end %>
                      <% end %>
                    <% end %>
                  <% end %>
                  <% if i > 0 %>
                    <%= "🔔" %><%= i %><%= "件 未承認の週休変更申請があります" %>
                  <% else %>
                    <%= "承認待ちの週休変更申請はありません" %>
                  <% end %>
              <% else %>
                <%= "週休変更申請はまだありません" %>
              <% end %>
            </div>
          <% end %>
        <% end %>
      </h2>
      

      <div class='list'>
        <li class='link-list'><%= link_to "グループの有給申請一覧", group_path(id: group.id) %></li>
        <li class='link-list'><%= link_to "グループの週休変更申請一覧", group_change_holidays_path(group_id: group.id) %></li>
        
        <% if current_user.position == "システム管理者"  %>
          <li class='link-list'><%= link_to "グループ情報の編集", edit_group_path(id: group.id) %></li>
        <% end %>
      </div>
    <% end %>
  </ul>
</div>

app/views/group/new.html.erb
<%= render partial: "header", locals: { user: @user } %>


<%= form_with model: @group, url: group_index_path, html: { method: :post }, local: true do |f| %>
     <%= render :partial => 'form', :locals => {:f => f}%>
<% end %>

app/views/group/show.html.erb
<%= render partial: "header", locals: { user: @user } %>


  <div class='group-info'>
    <h1 class='group-name'>
      <%= @group.group_name %>
    </h1>
    <h3 class="group-member">
      <% if @group.users.exists? %> 
          <% @group.users.each do |f| %>
              <%= f.user_name %>
          <% end %>
      <% else %>
          <div class='menber_name'>
            <span>グループメンバーがいません</span>
          </div>
      <% end %>
    </h3>
  </div>

<ul class='item-contents'>
  <div class='item-info'>   
    <% if @group_holidays.exists? %> 
    <div class="content-title"><%= paginate @group_holidays %></div>
      <% @group_holidays.each do |f| %>
        <%= link_to holiday_path(f.id), method: :get do %>
          <table class="request-table">
              <tr>
                  <th class="detail-item"><%= "名前" %></th>
                  <th class="detail-item"><%= "申請日" %></th>
                  <th class="detail-item"><%= "取得日" %></th>
                  <th class="detail-item"><%= "日/時" %></th>
                  <th class="detail-item"><%= "時間休・内訳" %></th>
                  <th class="detail-item"><%= "時間休・合計" %></th>
                  <th class="detail-item"><%= "事由" %></th>
                  <th class="detail-item"><%= "リーダー" %></th>
                  <th class="detail-item"><%= "部長" %></th>
                  <th class="detail-item"><%= "総務" %></th>
              </tr>
            <div class="formats">
              <tr>
                <td class="detail-value"><%= f.user.user_name %></td>
                <td class="detail-value"><%= f.updated_at.strftime('%Y/%m/%d') %></td>
                <td class="detail-value"><%= "" %><%= f.application_date.strftime('%Y/%m/%d') %>
                <td class="detail-value"><%= f.acquisition_days %></td>
                <% if f.holiday_time_start.nil? %> 
                      <td class="detail-value"><span>時間の指定なし</span></td>
                <% else %>
                      <td class="detail-value"><%= "start " %><%= f.holiday_time_start.strftime('%H') %>
                                          <%= "〜end " %><%= f.holiday_time_end.strftime( "%H" ) %></td>
                <% end %> 
                <td class="detail-value"><%= f.acquisition_time %>時間</td>
                <td class="detail-value"><%= f.reason %></td>
                  <% if Request.exists?(holiday_id: f.id) %> 
                        <% if Request.exists?(holiday_id: f.id, position: "リーダー") %>
                            <% request = Request.find_by(holiday_id: f.id, position: "リーダー") %>
                            <% if request.yes_no == "yes" %>
                              <td class="detail-value"><span>✅</span><%= request.user.user_name %></td>
                            <% elsif request.yes_no == "no" %>
                              <td class="detail-value"><span>❌</span><%= request.user.user_name %></td>
                            <% end %>
                        <% else %>
                              <td class="detail-value"><span>--</span></td>
                        <% end %>
                        <% if Request.exists?(holiday_id: f.id, position: "部長") %>
                            <% request = Request.find_by(holiday_id: f.id, position: "部長") %>
                            <% if request.yes_no == "yes" %>
                              <td class="detail-value"><span>✅</span><%= request.user.user_name %></td>
                            <% elsif request.yes_no == "no" %>
                              <td class="detail-value"><span>❌</span><%= request.user.user_name %></td>
                            <% end %>
                        <% else %>
                              <td class="detail-value"><span>--</span></td>
                        <% end %>         
                        <% if Request.exists?(holiday_id: f.id, position: "システム管理者") %>
                            <% request = Request.find_by(holiday_id: f.id, position: "システム管理者") %>
                            <% if request.yes_no == "yes" %>
                              <td class="detail-value"><span>✅</span><%= request.user.user_name %></td>
                            <% elsif request.yes_no == "no" %>
                              <td class="detail-value"><span>❌</span><%= request.user.user_name %></td>
                            <% end %>
                        <% else %>
                              <td class="detail-value"><span>--</span></td>
                        <% end %> 
                  <% else %>
                      <td class="detail-value"><span>--</span></td>
                      <td class="detail-value"><span>--</span></td>
                      <td class="detail-value"><span>--</span></td>
                  <% end %>
                </tr>
            </div>
          </table>
        <% end %>
      <% end %>
      <div class="content-title"><%= paginate @group_holidays %></div>
    <% else %>
        <div class='group-member'>
          <h2>有給休暇の申請はまだありません</h29>
        </div>
    <% end %>       
  </div>
</ul>